// angular-app/src/app/select/select.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.css']
})
export class SelectComponent implements OnInit {

  items = ['Toto', 'Titi', 'Tata'];
  selected = 'Toto';

  menuOpen = false;

  constructor() { }

  ngOnInit(): void {
  }

}

<div (click)="menuOpen = !menuOpen">{{ selected }}</div>

<div class="menu" *ngIf="menuOpen">
  <div class="item" *ngFor="let item of items" (click)="selected = item">
    {{ item }}
  </div>
</div>


<!-- <ng-template [ngIf]="menuOpen">
  <div class="menu">
    Menu
  </div>
</ng-template>
 -->

// vue-app/src/components/Select.vue
<template>
  <div @click="menuOpen = !menuOpen">{{ selected }}</div>

  <div class="menu" v-if="menuOpen">
    <div class="item" v-for="item of items" :key="item" @click="selected = item">
      {{ item }}
    </div>
  </div>
</template>

<script>
export default {
  name: 'Select',
  data() {
    return {
      items: ['Toto', 'Titi', 'Tata'],
      selected: 'Toto',
      menuOpen: false,
    };
  },
};
</script>

<style scoped>
  .menu {
    border: 1px solid black;
  }
</style>
