// angular-app/src/app/todos/todos.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { Todo } from './todo.model';

@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.css'],
})
export class TodosComponent implements OnInit {
  todos: Todo[] = [
    {
      id: Math.random(),
      title: 'ABC',
      completed: true,
    },
    {
      id: Math.random(),
      title: 'DEF',
      completed: false,
    },
  ];

  value = '';

  idTodoEdition: number | undefined;

  constructor() {
  }

  ngOnInit(): void {}

  addTodo(event: Event) {
    event.preventDefault();
    this.todos.unshift({
      id: Math.random(),
      title: this.value,
      completed: false,
    });
  }

  deleteTodo(todo: Todo) {
    const index = this.todos.indexOf(todo);
    this.todos.splice(index, 1);
  }

  @HostListener('document:click', ['$event'])
  clickOutside(event: Event) {
    if ((event.target as Element).classList.contains('todo-edit')) {
      return;
    }
    this.idTodoEdition = undefined;
  }
}

<!--
  Exercice 2 :
  Ecouter la saisi du champs todo-input (comme dans Helloworld)
  Ecouter le submit du formulaire et ajouter au tableau un élement
  {
    id: Math.random(),
    title: 'La valeur saisie dans le champ',
    completed: false,
  }
  (le composant se raffraichit tout seul)
-->
<form class="todo-form" (submit)="addTodo($event)">
  <input type="checkbox" class="todo-toggle-all" />
  <input class="todo-input" [value]="value" (input)="value = $any($event.target).value"  />
  <button>+</button>
</form>
<div class="todo-container">
  <!--
    Exercice 1 :
    avec *ngFor boucler sur le tableaux todos
    et afficher les todos comme ci-dessous
    - la checkbox doit être coché en fonction de la clé completed
    - la balise span doit afficher la valeur de la clé title
  -->
  <div class="todo-row" *ngFor="let todo of todos">
    <input type="checkbox" [checked]="todo.completed" />
    <span (dblclick)="idTodoEdition = todo.id" *ngIf="idTodoEdition !== todo.id">{{ todo.title }}</span>
    <input class="todo-edit" [value]="todo.title" (input)="todo.title = $any($event.target).value" *ngIf="idTodoEdition === todo.id" />
    <button (click)="deleteTodo(todo)">-</button>
  </div>
</div>

<!--
  Exercice Optionnel :
  Comme dans le projet précédent
  - Supprimer les todos au clic du bouton moins
  - Tout cocher / tout décocher
  - Pouvoir éditer au double-click
  - Le footer comme sur todomvc.com
-->

// vue-app/src/components/Todos.vue
<template>
  <form class="todo-form" @submit="addTodo($event)">
    <input type="checkbox" class="todo-toggle-all" />
    <input class="todo-input" v-model="value" />
    <button>+</button>
  </form>
  <div class="todo-container">
    <div class="todo-row" v-for="todo of todos" :key="todo.id">
      <input type="checkbox" v-model="todo.completed" />
      <span
        @dblclick="idTodoEdition = todo.id"
        v-if="idTodoEdition !== todo.id"
      >
        {{ todo.title }}
      </span>
      <input class="todo-edit" v-model="todo.title" v-else />
      <button @click="deleteTodo(todo)">-</button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      todos: [
        {
          id: Math.random(),
          title: 'ABC',
          completed: true,
        },
        {
          id: Math.random(),
          title: 'DEF',
          completed: false,
        },
      ],
      value: '',
      idTodoEdition: undefined,
    };
  },
  mounted() {
    document.addEventListener('click', this.handleDocumentClick);
  },
  beforeUnmount() {
    document.removeEventListener('click', this.handleDocumentClick);
  },
  methods: {
    addTodo(event) {
      event.preventDefault();
      this.todos.unshift({
        id: Math.random(),
        title: this.value,
        completed: false,
      });
    },
    deleteTodo(todo) {
      const index = this.todos.indexOf(todo);
      this.todos.splice(index, 1);
    },
    handleDocumentClick(event) {
      if (event.target.classList.contains('todo-edit')) {
        return;
      }
      this.idTodoEdition = undefined;
    },
  },
};
</script>
