// vue-app/src/components/MultiStateButton.vue
<script>
export default {
  name: 'MultiStateButton',
  props: {
    items: {
      type: Array,
      default: [],
    },
  },
  data() {
    return {
      index: 0,
    };
  },
  methods: {
    nextItem() {
      this.index = (this.index + 1) % this.items.length;
    },
  },
  render() {
    return <button onClick={this.nextItem}>{this.items[this.index]}</button>;
  },
};
</script>

// react-app/src/MultiStateButton.js
import React, { Component } from 'react'

export class MultiStateButton extends Component {
  state = {
    index: 0,
  }
  handleClick = () => {
    // const items = this.props.items ?? [];
    const { items = [] } = this.props;
    const index = this.state.index;
    this.setState({
      index: (index + 1) % items.length,
    });
  }
  render() {
    // const items = this.props.items ?? [];
    const { items = [] } = this.props;

    const index = this.state.index;

    return (
      <button className="MultiStateButton" onClick={this.handleClick}>
        {items[index]}
      </button>
    )
  }
}

export default MultiStateButton
