// vue-app/src/components/Todos.vue
<template>
  <form class="todo-form" @submit="addTodo($event)">
    <input type="checkbox" class="todo-toggle-all" />
    <input class="todo-input" v-model="value" />
    <button>+</button>
  </form>
  <div class="todo-container">
    <div class="todo-row" v-for="todo of todos" :key="todo.id">
      <input type="checkbox" v-model="todo.completed" />
      <span
        @dblclick="idTodoEdition = todo.id"
        v-if="idTodoEdition !== todo.id"
      >
        {{ todo.title }}
      </span>
      <input class="todo-edit" v-model="todo.title" v-else />
      <button @click="deleteTodo(todo)">-</button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      todos: [
        {
          id: Math.random(),
          title: 'ABC',
          completed: true,
        },
        {
          id: Math.random(),
          title: 'DEF',
          completed: false,
        },
      ],
      value: '',
      idTodoEdition: undefined,
    };
  },
  mounted() {
    document.addEventListener('click', this.handleDocumentClick);
  },
  beforeUnmount() {
    document.removeEventListener('click', this.handleDocumentClick);
  },
  methods: {
    addTodo(event) {
      event.preventDefault();
      this.todos.unshift({
        id: Math.random(),
        title: this.value,
        completed: false,
      });
    },
    deleteTodo(todo) {
      const index = this.todos.indexOf(todo);
      this.todos.splice(index, 1);
    },
    handleDocumentClick(event) {
      if (event.target.classList.contains('todo-edit')) {
        return;
      }
      this.idTodoEdition = undefined;
    },
  },
};
</script>

// react-app/src/Todos.js
import React, { Component } from 'react';

export class Todos extends Component {
  state = {
    todos: [
      {
        id: Math.random(),
        title: 'ABC',
        completed: true,
      },
      {
        id: Math.random(),
        title: 'DEF',
        completed: false,
      },
    ],
    value: '',
    idTodoEdition: undefined,
  };
  handleNewTodoChange = (event) => {
    this.setState({
      value: event.target.value,
    });
  };
  handleSubmit = (event) => {
    const { todos, value } = this.state;
    event.preventDefault();
    this.setState({
      todos: [
        {
          id: Math.random(),
          title: value,
          completed: false,
        },
        ...todos,
      ],
    });
  };
  handleDelete = (todo) => {
    const { todos } = this.state;
    this.setState({
      todos: todos.filter((t) => t.id !== todo.id),
    });
  };
  handleToggleAll = (event) => {
    const { todos } = this.state;
    this.setState({
      todos: todos.map((t) => ({
        ...t,
        completed: event.target.checked,
      })),
    });
  };
  render() {
    const { todos, value, idTodoEdition } = this.state;
    return (
      <div className="Todos">
        <form class="todo-form" onSubmit={this.handleSubmit}>
          <input
            type="checkbox"
            class="todo-toggle-all"
            onChange={this.handleToggleAll}
          />
          <input
            class="todo-input"
            value={value}
            onChange={this.handleNewTodoChange}
          />
          <button>+</button>
        </form>
        <div class="todo-container">
          {todos.map((t) => (
            <div class="todo-row">
              <input type="checkbox" checked={t.completed} />
              {idTodoEdition !== t.id ? (
                <span>{t.title}</span>
              ) : (
                <input class="todo-edit" />
              )}
              <button onClick={() => this.handleDelete(t)}>-</button>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default Todos;
