// vue-app/src/components/UserForm.vue
<template>
  <form @submit="create($event)">
  <p>
    Prénom :
    <!-- <input type="text" name="prenom" :value="user.prenom" @input="user.prenom = $event.target.value" /> -->
    <input type="text" name="prenom" v-model="user.prenom" />
  </p>
  <p>
    Email :
    <!-- <input type="email" name="email" :value="user.email"  @input="updateEmail($event)" /> -->
    <input type="email" name="email" v-model="user.email" />
  </p>
  <p>
    Compte actif :
    <!-- <input type="checkbox" name="active" :checked="user.isActive" @change="user.isActive = $event.target.checked" :class="{active: user.isActive}" /> -->
    <input type="checkbox" name="active" v-model="user.isActive" :class="{active: user.isActive}" />
  </p>
  <p>
    <button>Envoyer</button>
  </p>
</form>

</template>

<script>
export default {
  name: 'UserForm',
  data() {
    return {
      user: {
        prenom: 'Romain',
        email: 'romain.bohdanowicz@formation.tech',
        isActive: true,
      },
    };
  },
  methods: {
    create(event) {
      event.preventDefault();
    },
    updateEmail(event) {
      this.user.email = event.target.value;
    }
  }
}
</script>

// angular-app/src/app/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.css']
})
export class UserFormComponent implements OnInit {

  user = {
    prenom: 'Romain',
    email: 'romain.bohdanowicz@formation.tech',
    isActive: true,
  };

  constructor() { }

  ngOnInit(): void {
  }

  create(event: Event) {
    event.preventDefault();
    console.log(this.user);
  }

  updateEmail(event: Event) {
    const target = event.target as HTMLInputElement;
    this.user.email = target.value;
  }
}

<form (submit)="create($event)">
  <p>
    Prénom :
    <input type="text" name="prenom" [value]="user.prenom" (input)="user.prenom = $any($event.target).value" />
  </p>
  <p>
    Email :
    <input type="email" name="email" [value]="user.email"  (input)="updateEmail($event)" />
  </p>
  <p>
    Compte actif :
    <input type="checkbox" name="active" [checked]="user.isActive" [class.active]="user.isActive" />
  </p>
  <p>
    <button>Envoyer</button>
  </p>
</form>
